apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
     labels:
       app: api
    spec:
      initContainers:
        - name: migrations
          image: migrations:lab3
          imagePullPolicy: Never
          command: ["prisma", "db", "push"]
          env:
            - name: DATABASE_URL
              value: "postgres://user:pass@postgres-service:5432/lab"
      containers:
        - image: api:lab3
          imagePullPolicy: Never
          name: api
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "postgres://user:pass@postgres-service:5432/lab"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq-service:5672"

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: api